" Jacks vimrc file

" Vim Plug packages
" install plug using
" Unix -> curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
" Windows -> iwr -useb https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim ni $HOME/vimfiles/autoload/plug.vim -Force
" Then use :PlugInstall to install the new plugins
call plug#begin()
Plug 'morhetz/gruvbox'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
call plug#end()

" Buffer bar always on
let g:airline#extensions#tabline#enabled = 1

colorscheme gruvbox

" Other setup
set number
set background=dark
set backspace=2	
set t_Co=256
set tabstop=4
set shiftwidth=4
set guifont=lucida_Console:h14
set spell spelllang=en_us
set complete+=kspell
